### ISSUE TITLE
Changing import directory relativity

### ISSUE THREAD

**Issue by rs-eytan** [kristijanhusak/vim-js-file-import#12]
First of all, thank you very much for this plugin. I had a quick question on the import paths.

I would like to change the import path from

`../../../components/{import}`

to

`components/{import}`

Is this possible?

**Comment by kristijanhusak** [comment]
No not at this moment. I'll make it configurable.

**Comment by kristijanhusak** [comment]
I just added an option to do this. 
Add `let g:js_file_import_from_root = 1` to your vimrc, and files will be imported relatively to your current working directory instead of current file. Give it a test and let me know if it works ok.

**Comment by rs-eytan** [comment]
@kristijanhusak thank you very much. its almost perfect. right now my import looks like:

`src/constants/...`

I'd prefer it not to have the src either? Maybe I can manually set a root?

I did this locally and seem to work.

added to `plugin/vim-js-file-import.vim`

```vimscript
let g:js_file_project_root = get(g:, 'js_file_project_root', '/')
```

changed `jsfileimport#utils#_get_file_path(filepath) abort`

```vimscript
  if g:js_file_import_from_root
    let root = g:js_file_project_root
    return substitute(fnamemodify(a:filepath, ':p:r'), getcwd().root, '', '')
  endif

  ...
```

This seems to work perfectly for me but it might not be what you want for your package.

**Comment by rs-eytan** [comment]
@kristijanhusak perfect. thank you. and if you ever need help, i'll try to jump in. i'm loving the package 💯

**Comment by kristijanhusak** [comment]
No problem. Closing, since it's resolved.
