### ISSUE TITLE
Option to have " instead of ' for the import line

### ISSUE THREAD

**Issue by realestninja** [kristijanhusak/vim-js-file-import#13]
Hi, would it be possible to add an option for the import path to be in " instead of '? Some projects have guidelines that expect " over '. Right now I use eslint fixer everytime after doing an import but it would save some time in the long run if the import string was already the way I need it.

Example:
`import H3 from "../../typography/H3";`
instead of 
`import H3 from '../../typography/H3';`

I took a look at the plugin but couldn't identify the section that I would need to edit to make this possible.

Have a nice day!

PS: great plugin, it's a blessing!

**Comment by kristijanhusak** [comment]
Yeah sure. I'll add it.
Didn't really thought about it because i use `'` all the time.
Will keep you posted.

**Comment by kristijanhusak** [comment]
@realestninja i added it.
Check this section in readme https://github.com/kristijanhusak/vim-js-file-import#using-double-quotes.

Let me know if it works.

**Comment by realestninja** [comment]
Hey it works perfectly :) Thank you so much!
