### ISSUE TITLE
Enable option for keeping file extension

### ISSUE THREAD

**Issue by micburks** [kristijanhusak/vim-js-file-import#15]
Thanks for all the hard work! I think this is a great tool for auto-imports. I like having the alternative to how imports are done with `deoplete`.

The one gripe I have is that I actually use file extensions in my imports. In Node's new support for ES modules, the file extension plays an important part in how the import is treated (See [Node docs](https://nodejs.org/api/esm.html#esm_enabling)).

Something like
```vim
let g:js_file_import_strip_extension = 0 " Defaults to '1' for backwards compatibility
```
similar to `deoplete`'s option would be super useful for Node developers

Apologies if this is already possible, I couldn't find any option to do this.

**Comment by kristijanhusak** [comment]
@micburks I added it, but i'll need you to test it to see if it works ok.
Just add this setting to vimrc:
```vimL
let g:js_file_import_strip_file_extension = 0
```
If it works ok, let me know here and close the issue.

**Comment by micburks** [comment]
Works great! Thanks for the quick turnaround. Best of luck
