### ISSUE TITLE
Open file in new tab

### ISSUE THREAD

**Issue by gfsd3v** [kristijanhusak/vim-js-file-import#16]
Hi.

First of all thanks for the awesome plugin.

Is it possible to make the go to definition open the file/directory in a new tab ? Didn't found anything about this is the Docs/Issues.

Thanks in advance.

**Comment by kristijanhusak** [comment]
Hi,

you can use vim built in functionality to achieve this. For example, to map it to <Leader>], you would have something like this:

```vim
nmap <Leader>] <C-W>T<Plug>(JsGotoDefinition)
```

Basically <C-w>T opens the same file you are editing in new tab, and then executes plugin mapping. If you would want to open in vertical split, it woult be `<C-W>v<Plug>(JsGotoDefinition)`

**Comment by gfsd3v** [comment]
Thanks for the help, it worked like a charm (:
