### ISSUE TITLE
Feature Request | ig goes activated on import statement.

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#19]
Hi @kristijanhusak!

I was wondering if it would be possible to make `<Leader>ig` also go to the definition if it's pressed over the include statement.

For example, if I have the cursor somewhere on over import or anywhere on that line and I hit `<Leader>ig`, it would open the lib file buffer.

`imp|ort { MyComponent } from './components/lib'`

**Comment by kristijanhusak** [comment]
I introduced passing custom word to the import/goto commands, so this is something you can do yourself. Basically:

1. Get the current line and parse the word you want to jump to
2. Execute the command with that word, in this case it would be `:JsGotoDefinition lib`

**Comment by nkabbara** [comment]
@kristijanhusak when I trued something `JsGotoDefinition lib` it says trailing characters. As if it's not expecting to have an argument. Is this already implemented?

**Comment by kristijanhusak** [comment]
That's odd. Is `lib` a folder? 
What happens if you write down `lib` into the buffer and try to go to definition in the old way?

**Comment by nkabbara** [comment]
> That's odd. Is lib a folder?

Nope.

> What happens if you write down lib into the buffer and try to go to definition in the old way?

It goes there fine.

![v](https://user-images.githubusercontent.com/31865/78739671-63e0aa00-791a-11ea-9370-1d7158636d65.gif)

**Comment by kristijanhusak** [comment]
I can't reproduce it. Does it happen for some other words?
Also, do you have any more files or folders that are called `lib`?

I would appreciate if you would debug this. Here are the steps:
1. Find plugin in your plugins directory, open `autoload/jsfileimport.vim`, and comment out all lines that are try/catch. So basically line 28, and lines from 61 to 66. Then try to reproduce this. It should give more uglier but detailed error.

**Comment by nkabbara** [comment]
> I would appreciate if you would debug this.

Anytime. I commented them out, but they were on different lines for me: 58, 106 and 143.

Error is still the same. Nothing changed. I verified that the comments took effect by causing other errors and I see more detailed errors for the other valid errors.

Let me know if you need further debugging.

-Nash

**Comment by kristijanhusak** [comment]
How are the lines different? When did you do an update last time?

Can you test with some other words?

**Comment by nkabbara** [comment]
It seems to work after the latest update. Awesome, thanks, I'll figure out how to make it detect import line and go to imported file!

**Comment by nkabbara** [comment]
@kristijanhusak how can I call JsGotoDefinition(filename) in vimrc with the context of the current buffer?

The pseudocode for what I'm thinking:
 
function! LoadImportFileUnderCursor(currentLine)
   "parse out the path from currentLine
   "assign to somevar
  JsGotoDefinition a:somevar
endfunction

**Comment by kristijanhusak** [comment]
Assuming your line looks something like this:
```js
import MyComponent from './components/MyComponent';
```

Something like this should do the trick:
```vimL
function! GotoDefinition()
  let current_line = getline('.')
  let matches = matchlist(current_line, '^import \(\w\+\) from .*$')
  if empty(matches)
    return
  endif
  
  exe 'JsGotoDefinition '.matches[1]
endfunction

nnoremap <Leader>g :call GotoDefinition()<CR>
```
Haven't tested it though, so adjust accordingly if needed.

**Comment by nkabbara** [comment]
Thank you so much! I'll give it a try later.
