### ISSUE TITLE
Components named differently than their definition

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#20]
If I have this import:

`import DiscoverScreen from './screens/discover'`

if I hit <Leader>ig on the component below, I get 'tag not found error'. I'm guessing this is because the component in discover file is named differently than DiscoverScreen (it's a default export). Is it possivle for JFI to figure out at least to go to the file from the import statement if it's available? So in this specific instance, ./screens/discover file would open.

`<DiscoverScreen />`

**Comment by kristijanhusak** [comment]
Name of the component is too different from the actual filename.
If it would be called ScreenDiscovered, there could be a possibility to figure that out, but I think that's a bit too much. It can cause undesired results in some cases.
As I wrote in the comment here https://github.com/kristijanhusak/vim-js-file-import/issues/19#issuecomment-607718374, you can have your small parser that will figure the component name, and just call the command with that. In this example having it parse `discover` and doing `JsGotoDefinition discover` should be sufficient.
