### ISSUE TITLE
Partial/Full Imports

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#22]
Hi @kristijanhusak,

I noticed when trying to import a function, say a hook, it's assuming that it's the default import. Possible to make it a partial import instead based on the export? Or at least configure the default import to always be a partial.

In the image below I want the `useAuth` import to be like so `import { useAuth } from...` when I hit `<Leader>if` over useAuth on line 12. Possible with the current version?

![import](https://user-images.githubusercontent.com/31865/78628884-2e28bc00-785b-11ea-8992-b2bbff1d14e1.png)

**Comment by kristijanhusak** [comment]
does `useAuth` exist in your tags file? If it does, can you give me the content of that line ? You can blur file path if needed, not really important.

**Comment by nkabbara** [comment]
Yup.

`useAuth	/Users/nkabbara/.../src/context/auth-context.js	/^function useAuth() {$/;"	f	line:44	language:JavaScript	signature:()`

**Comment by kristijanhusak** [comment]
Ok, and in you auth-context.js file, how is it exported?

**Comment by nkabbara** [comment]
`export {AuthProvider as default, useAuth}`

Also tried:

`export {AuthProvider, useAuth}`

Thanks! Let me know if you need further debugging!

**Comment by kristijanhusak** [comment]
I didn't consider that syntax as partial export. I fixed it now. Do an update and test.

**Comment by nkabbara** [comment]
Hm, doesn't seem to be working and I have the updated version (0833c46aa157ca3553fdf8b9f555f455d474530b)

My export looks like this: `export {AuthProvider, useAuth}`. It still imports it like this: `import useAuth from './auth-context'`.

My tags file useAuth line looks like so: useAuth	`/Users/nkabbara/.../src/context/auth-context.js	/^function useAuth() {$/;"	f	line:60	language:JavaScript	signature:()`

**Comment by kristijanhusak** [comment]
I just updated my tests to test the the same functionality.
Your ctags syntax is strange, are you using `universal ctags` ?

What is the output of this for you:
`echo taglist('^useAuth$')`

**Comment by nkabbara** [comment]
> Your ctags syntax is strange, are you using universal ctags ?

Yes, but it could be due to the fields option below. I forgot why I had to add that at some point. Anywa, I commented that out and tried again and still it failed to add braces. 

```
let g:gutentags_ctags_extra_args = [
      \ '--tag-relative=yes',
      \ '--fields=+ailmnS',
      \ ]
```

> echo taglist('^useAuth$')

With the ctags_extra_args above:
```
[{'cmd': '/^function useAuth() {$/', 'static': 0, 'name': 'useAuth', 'line': '54', 'l
anguage': 'JavaScript', 'kind': 'f', 'signature': '()', 'filename': '/Users/nkabbara/
dev/.../src/context/auth-context.js'}]
```

Without the ctags_extra_args above:
```
[{'cmd': '/^function useAuth() {$/', 'static': 0, 'name': 'useAuth', 'kind': 'f', 'fi
lename': '/Users/nkabbara/dev/.../src/context/auth-context.js'}]
```

**Comment by kristijanhusak** [comment]
[partial-project.zip](https://github.com/kristijanhusak/vim-js-file-import/files/4466332/partial-project.zip)

Here's a sample project where i tried to simulate your code.
Try to import useAuth here in `auth-context.js` and let me know if it works or not.

**Comment by nkabbara** [comment]
> Try to import useAuth here in auth-context.js and let me know if it works or not.

Works fine with the ctags you provided. Does not work with my ctags.

Also, it works with my ctags when exporting functions in their declaration like so:

```
export function useAuth() {
  console.log('Use auth')
}

```

But does not work if the export like `export { AuthProvider as default, useAuth }
`

Does that give any clues as to what might be happening?

**Comment by kristijanhusak** [comment]
Please attach your version of tags

**Comment by nkabbara** [comment]
Attached!

[tags.txt](https://github.com/kristijanhusak/vim-js-file-import/files/4484696/tags.txt)

side note: when cursor is over the parenthesis, ie `useAuth(|)`, you get the error below. I'm thinking JSF should be hook aware. Let me know if you'd like me to open a separate issue with this.

<img width="688" alt="Screen Shot 2020-04-15 at 10 11 29 PM" src="https://user-images.githubusercontent.com/31865/79410525-4d63cf80-7f66-11ea-8323-a0b5a68f6d31.png">

**Comment by kristijanhusak** [comment]
Problem is that paths in the ctags are absolute, and not relative. I fixed it.
Is there any specific reason why you add these additional arguments to ctags to generate different format?

Not sure what you mean by hook aware, but I assume you think that it should figure out the import in the parentheses. JSF is using vim's built in `expand('<cword>`)` to get the word under cursor, which in this case is not that.

**Comment by nkabbara** [comment]
Nice!!! Thank you!

> Is there any specific reason why you add these additional arguments to ctags to generate different format?

At one point it was required by some plugin, but I had since removed it and kept the settings. But the reason behind absolute paths, is because I configured my tags to be stored in a central instead of project dir (gutentags_cache_dir). 

> JSF is using vim's built in expand('<cword>)` to get the word under cursor, which in this case is not that

No worries! Not a big deal. 

Thanks again and have great week!
