### ISSUE TITLE
Potential SortJsFileImport bug

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#23]
Hi @kristijanhusak 

I have prettier formatter that formats import similar to this:

```
import {
  CircleButton,
  Button,
  Spinner,
  FormGroup,
  Centered,
} from './components/lib'
```
SortJsFileImport sorts it like so:

```
import {jsx} from '@emotion/core'

  Button,
  Centered,
  CircleButton,
  FormGroup,
  Spinner,
import Logo from './components/logo'
import React, {useState} from 'react'
import styled from '@emotion/styled'
import useCallbackStatus from './utils/use-callback-status'
import VisuallyHidden from '@reach/visually-hidden'
import {
import {Dialog} from '@reach/dialog'
import {useAuth} from './context/auth-context'
} from './components/lib'
```

This might be a pretty involved fix and it's not critical for me. I can disable sorting, but wanted to bring it to your attention.

**Comment by kristijanhusak** [comment]
Yeah there's already an issue for that. https://github.com/kristijanhusak/vim-js-file-import/issues/11 . I never spend a lot of time on it since it's not crucial.
