### ISSUE TITLE
Unexpected JsGoToDefinition behavior on Unsaved files

### ISSUE THREAD

**Issue by nkabbara** [kristijanhusak/vim-js-file-import#24]
When you make changes to a buffer and you try to `<Leader>ig` on a component, JFI moves the cursor to the start of the line and and fails silently without a message.

To reproduce:

1. Make changes to a buffer
2. Put cursor over a component and exec JsGoToDefinition

Expected:
An error message telling me file is not saved and to save file.

What happened:

Cursor moved to column 1.

**Comment by kristijanhusak** [comment]
Do you have `set hidden` in your vimrc?

**Comment by nkabbara** [comment]
> Do you have set hidden in your vimrc? 

Nope.

> What's output of echo hidden ?

0

**Comment by kristijanhusak** [comment]
You must have it set `hidden` to make it work. Same will happen to you if you use build in tag jumping functionality.

**Comment by nkabbara** [comment]
Hi @kristijanhusak,

> You must have it set hidden to make it work

Yes, that is if I wanted the hidden behavior. I think if a user has set it to false, they would expect the same behavior as when trying to leave the buffer to another one with unsaved changers. i.e. a message asking them to save the buffer.

Currently JFI fails silently.

**Comment by kristijanhusak** [comment]
Makes sense. I fixed it.

**Comment by nkabbara** [comment]
Awesome! Works great!
