### ISSUE TITLE
Using more shallow imports when possible

### ISSUE THREAD

**Issue by alextes** [kristijanhusak/vim-js-file-import#25]
In the case of yarn workspaces, packages often require code from one another. So if we have a `module-b` like so:
`module-b/index.js`:
```
const fnA = require('./way/past/index.js');
module.exports = { fnA };
```

`module-a` might require this function simply by writing:
```
const { fnA } = require('module-b');
```

This works because yarn manages these modules and has created a symlink in `node_modules` like so `/node_modules/module-b -> ../module-b`.

However, when importing something from module-b, from a module somewhere in module-a say `module-a/src/that-module.js`, the import can be as simple as:
```
const { fnA } = require('module-b');
```
but the plugin will infer:
```
const { fnA } = require('../../module-b/way/past/index.js');
```
So two things that might be improved:
1. `module-b` has an `index.js` with `fnA`, prefer the shallow import from there over traversing into the module's source. Somehow this does work with modules from npm 🤔 .
2. prefer importing from node_modules/module-b over a folder named `module-b`.

Do those suggestions make sense? What do you think? This is a long way to say, feature request to work with yarn workspaces 😄 .

Thanks for the great plugin 🙌 !

**Comment by kristijanhusak** [comment]
Do you even get a "shallow" option when you force import list, or you only get the one deeper?
