### ISSUE TITLE
Can't ever find any file or package to import from

### ISSUE THREAD

**Issue by coaxial** [kristijanhusak/vim-js-file-import#29]
I followed the instructions by installing universal-stags on Ubuntu 20.04 (using a snap) and adding these to my .vimrc:

```
Plug 'ludovicchabant/vim-gutentags'
Plug 'kristijanhusak/vim-js-file-import', {'do': 'npm install'}
```

Now when I go into a `.ts` file, and I do `leader if` on a symbol that isn't imported yet, the plugin never ever finds the symbol and prompts me for the path. And after I enter the path, for instance `./app.component`, it then goes and clobbers it all to insert `../../../../app`.

I'm not sure what I'm missing here but I'm definitely not getting the result I'd expect from that package.

Relevant .vimrc section: https://github.com/coaxial/dotfiles/blob/master/.vimrc#L44-L46

Tried with nvim v0.4.3 and vim v8.1

**Comment by kristijanhusak** [comment]
Are you able to jump to any tag with Ctrl + ] ?

**Comment by coaxial** [comment]
For some symbols, yes. For others, I get `E426: tag not found: <the symbol>`.

**Comment by kristijanhusak** [comment]
Are you able to import those symbols thay are found?

**Comment by coaxial** [comment]
Sort of. Some of the symbols exported by a package, it can find (but gives me a list with cryptic entries when there really isn't one export with that name in the package), and then instead of importing from `'package'`, it inserts `../../../../node_modules/package/deep/deeper/symbol` rather than `'package'`.

**Comment by kristijanhusak** [comment]
It lists everything that it finds in the tags file. You should not generate tags for the `node_modules`. Add `let g:gutentags_ctags_exclude = ['node_modules']` to your vimrc, restart Vim and run `:GutentagsUpdate!`, then give it another try.
When prompted for import, choose the one from package.json.
Note that this plugin doesn't do any parsing of the JS or anything, it just relies on the tags file, thus it doesn't know to do any deeper imports of the packages from node modules.

**Comment by coaxial** [comment]
Alright, thank you!
