### ISSUE TITLE
Vue supporting

### ISSUE THREAD

**Issue by timsofteng** [kristijanhusak/vim-js-file-import#30]
Hello. Does this plugin work with vue and with alias paths as '@/сomponents/example'?
Thanks.

**Comment by kristijanhusak** [comment]
I don't think Vue is supported, never tried it. Alias paths doesn't work by default, you can set something up with this https://github.com/kristijanhusak/vim-js-file-import/blob/master/doc/vim-js-file-import.txt#L209

**Comment by kristijanhusak** [comment]
I added support for Vue, but it is not working 100% ok like for regular js.
1. It doesn't handle alias paths
2. If there aren't any imports in the file, and when you try to import the first thing, it will import it at 1st line. It is not aware of the `<script>` tag
3. Probably more issues, wasn't able to catch it.

So it's more-less working, but nothing fancy.

**Comment by timsofteng** [comment]
> I added support for Vue, but it is not working 100% ok like for regular js.
> 
> 1. It doesn't handle alias paths
> 2. If there aren't any imports in the file, and when you try to import the first thing, it will import it at 1st line. It is not aware of the `<script>` tag
> 3. Probably more issues, wasn't able to catch it.
> 
> So it's more-less working, but nothing fancy.

Thanks for fast response.
Is it any way to fix this issues?

**Comment by kristijanhusak** [comment]
Yeah, 2. should be fairly easy. For 1, where does configuration for this lives? Is that a webpack thing or?

**Comment by kristijanhusak** [comment]
@timsofteng I added some better support for Vue, but I wasn't able to test it in the real life project, since I don't develop in vue. I used this https://github.com/gothinkster/vue-realworld-example-app for testing.

Check this part of readme https://github.com/kristijanhusak/vim-js-file-import#vue-support , and give it a test to see how it works.

**Comment by timsofteng** [comment]
> @timsofteng I added some better support for Vue, but I wasn't able to test it in the real life project, since I don't develop in vue. I used this https://github.com/gothinkster/vue-realworld-example-app for testing.
> 
> Check this part of readme https://github.com/kristijanhusak/vim-js-file-import#vue-support , and give it a test to see how it works.

Thanks. I'll test it tomorrow.
By the way could I use go to file feature (gf) with this plugin?

**Comment by kristijanhusak** [comment]
You can use jump to definition via `<Plug>(JsGotoDefinition)`, if that's what you are talking about.
