### ISSUE TITLE
Can't open file /tmp/{folder}/{number}

### ISSUE THREAD

**Issue by whatever555** [kristijanhusak/vim-js-file-import#31]
When I run <leader>if i get some variation of following error message in vim:  
`Vim(let):E484: Can't open file /tmp/vSuL01s/5`  

It seems that the subfolder it is looking for does not exist:  
![image](https://user-images.githubusercontent.com/1413475/102600918-58838680-4117-11eb-90c1-cf0065054528.png)
  
I've tried setting my shell to `bash`, `zsh` and `sh` in my `.vimrc` file

**Comment by kristijanhusak** [comment]
Your working directory is `/tmp`?

**Comment by whatever555** [comment]
> Your working directory is `/tmp`?
  

working directory is /home/(user}/dev/{projectname}/

**Comment by kristijanhusak** [comment]
I'm not doing anything with tmp folder. Can you check your `tags` file to see if it has reference to these files in tmp folder?

**Comment by whatever555** [comment]
I've tried deleting my tags file and the error still occurs.  
It seems very similar to this error (although i am on ubuntu, not windows) and looks to be caused by some shell setting :thinking: https://github.com/google/vim-codefmt/issues/106  
  
Another similar issue posted here: https://badsimplicity.com/2013/11/05/vim-fish-e484-cant-open-file-tmpvrdnvqe0-error/

**Comment by whatever555** [comment]
I think it could be related to this line where the shell is set to sh: https://github.com/kristijanhusak/vim-js-file-import/blob/master/autoload/jsfileimport/utils.vim#L229  
Will try investigate a little now

**Comment by whatever555** [comment]
some further info:  
I am generating my tags file using gutentags. I can't seem to find any direct reference to the /tmp folder there...  

It is failing on this line: https://github.com/kristijanhusak/vim-js-file-import/blob/master/autoload/jsfileimport.vim#L127  
the l:rgx variable is = 
```{'import': 'import __FNAME__ from ''__FPATH__''', 'partial_export': 'export\s*\(\(default\)\@!\
w\+\s*\<__FNAME__\>\|\_[[:blank:]]\{-\}{\_[^}]\{-\}\<__FNAME__\>\_[^}]\{-\}}\)', 'default_expor
t': 'export\s*default.\{-\}', 'existing_path_for_full': '^import\s*\zs{\s*\_[^''"]\{-\}\s*}\ze\
s*from\s*[''"]__FPATH__[''"];\?$', 'lastimport': '^import\s\_[^''"]\{-\}from.*;\?$', 'select_fo
r_sort': '^import\s*\zs.*\ze\s*from.*;\?$', 'type': 'import', 'existing_path': '^import\s*[^{''
"]\{-\}{\s*\zs\_[^''"]\{-\}\ze\s*}\s*from\s*[''"]__FPATH__[''"];\?$', 'import_name': '^\(import
\)\s*\(\<[^''"]\{-\}\>\)\s*from\s*', 'existing_full_path_only': '^import\s*\zs\<[^''"]\{-\}\>\z
e\s*from\s*[''"]__FPATH__[''"];\?$', 'is_single_import': '^\import\(\s\|\n\)\{-\}{\?\(\s\|\n\)\
{-\}\<__FNAME__\>\(\s\|\n\)\{-\}}\?\(\s\|\n\)\{-\}from\(\s\|\n\)\{-\}[''"][^''"]*[''"];\?', 'ch
eck_import_exists': '^import\s*\_[^''"]\{-\}\<__FNAME__\>\_[^''"]\{-\}\s*from'}
```  
tag_fn_name = 
`jsfileimport#tags#_get_tag`
a:name = 
`Reset`
a:show list = 
`0`

**Comment by whatever555** [comment]
replacing this line https://github.com/kristijanhusak/vim-js-file-import/blob/master/autoload/jsfileimport/utils.vim#L186  

with:  
```
  let l:foo = substitute(a:cmd, '""', '"', "")
  echom l:foo
  let l:cmd_output = systemlist(l:foo)
```  
makes it functional

**Comment by kristijanhusak** [comment]
You are using fish shell?

**Comment by kristijanhusak** [comment]
I figured it out. There was an extra double quote for silversearcher-ag call that I introduced with recent changes. I fixed it. Please pull latest changes and give it a try.

Thanks for debugging it, it helped a lot.

**Comment by whatever555** [comment]
> I figured it out. There was an extra double quote for silversearcher-ag call that I introduced with recent changes. I fixed it. Please pull latest changes and give it a try.
> 
> Thanks for debugging it, it helped a lot.

:+1:  I'll give it another go later. Thanks!

**Comment by whatever555** [comment]
Seems to be working well! Cheers :+1:
