### ISSUE TITLE
Node.js ESM not supported

### ISSUE THREAD

**Issue by hoschi** [kristijanhusak/vim-js-file-import#32]
Or do I miss something perhaps?

Considering the following file `src/browser.mjs`:
```js
import { chromium } from "playwright"

export async function initBrowser() {
    const browser = await chromium.launch({
        headless: true,
    })
    const context = await browser.newContext()

    return { browser, context }
}
```

and another file `src/bin.mjs`:
```js

initBrowser()
```

Running `JsFileImport` creates:
`import initBrowser from './browser';`
instead of correct:
`import {initBrowser} from './browser.mjs';`

Running `JsFixImports` gives just an error: `Vim(let):E474: Attempt to decode a blank string`

I updated the plugin minutes ago. Tags File line of `initBrowser`:
`initBrowser	src/browser.mjs	/^export async function initBrowser() {$/;"	f`

**Comment by kristijanhusak** [comment]
mjs is not supported at this moment. It should be a simple fix.

**Comment by kristijanhusak** [comment]
I pushed a support for mjs + fix for the import.

Fix imports were not working because eslint was a bit outdated.

Please pull latest changes, do `npm install` in the plugin directory and give it another test.

**Comment by hoschi** [comment]
Better! It still creates imports without file extension `import initBrowser from './browser';` instead of `./browser.js`.

**Comment by hoschi** [comment]
I also found out that you just can add `"type": "module"` in your `package.json` to keep normal `.js` files. So supporting `.mjs` is probably not worth the time.

**Comment by kristijanhusak** [comment]
You can add this to your vimrc to make it import with extension:
```
let g:js_file_import_strip_file_extension = 0
```
