### ISSUE TITLE
weird suggestion list when importing some simple methods

### ISSUE THREAD

**Issue by samchan0221** [kristijanhusak/vim-js-file-import#34]
```
import React from 'react';

export const Testing = () => {
    const [a,b] = useEffect(effect);
    
    return(
        <div/>
    );
}
```

When I try to import useEffect form 'react', the list turns out to be like that:
![image](https://user-images.githubusercontent.com/36394128/121069670-5534a200-c800-11eb-9326-4c511a0f7783.png)

**Comment by kristijanhusak** [comment]
How are you generating tsgs file? If you use gutentags, add node_modules and .next folder to wildignore.

**Comment by samchan0221** [comment]
> How are you generating tsgs file? If you use gutentags, add node_modules and .next folder to wildignore.

I have `:set wildignore+=*/node_modules/*,*/.next/*`
but they are still here.

**Comment by kristijanhusak** [comment]
I'm having these for node_modules:
```vim
set wildignore+=*node_modules*,**/node_modules/**
```
And it works.

Are you using gutentags? Because it picks up these settings. If you do it manually, it does not respect these settings.

**Comment by samchan0221** [comment]
> I'm having these for node_modules:
> 
> ```viml
> set wildignore+=*node_modules*,**/node_modules/**
> ```
> 
> And it works.
> 
> Are you using gutentags? Because it picks up these settings. If you do it manually, it does not respect these settings.

Yes I'm using gutentags, I followed your wildignore and those wrong suggestions went away. However it still won't find the 'react' module for me so I have to type myself :$
![image](https://user-images.githubusercontent.com/36394128/121641738-277e8000-cac2-11eb-8c1d-11a5533ec046.png)

**Comment by kristijanhusak** [comment]
This package is limited to what's in the `tags` file, which means that anything that's in `node_modules` folder is not read. I explained it more briefly [here](https://github.com/kristijanhusak/vim-js-file-import/issues/27#issuecomment-695754078)

**Comment by samchan0221** [comment]
> This package is limited to what's in the `tags` file, which means that anything that's in `node_modules` folder is not read. I explained it more briefly [here](https://github.com/kristijanhusak/vim-js-file-import/issues/27#issuecomment-695754078)

I see, so I'd better use LSP for this kind of import. Thank you anyways, it is still a good plugin.
