### ISSUE TITLE
Key does not exist for 'telescope .actions': get_selected_entry

### ISSUE THREAD

**Issue by alexhwoods** [kristijanhusak/vim-js-file-import#37]
Nice work on this plugin, it's awesome!

I have an import with 2 tags, using the default UI works fine
```
Select file to import:
1) bar.ts - /^export const hello = "hello-bar"$/
2) foo.ts - /^export const hello = "hello-foo"$/
3) Enter path to file or package name manually for word "hello"
Type number and <Enter> or click with the mouse (q or empty cancels):
```

But with telescope, when I select an entry, I get this
```
E5108: Error executing lua ...im/plugged/telescope.nvim/lua/telescope/actions/init.lua:29: Key does not exist for 'telescope
.actions': get_selected_entry
```

- nvim version v0.5.1
- `:PlugSnapshot` shows that I have commit `7294924` for telescope, and commit `2bc10f` for vim-js-file-import.
- MacOS Big Sur, 11.2 (Apple M1)

**Comment by kristijanhusak** [comment]
I haven't used telescope in a while, so it's probably outdated. I'll take a look.

**Comment by kristijanhusak** [comment]
Should be fixed now.

**Comment by alexhwoods** [comment]
Sweet, taking a look 😃

**Comment by alexhwoods** [comment]
Yep, you got it.

Thank you!
