### ISSUE TITLE
Takes 30 seconds.  Cannot find package.

### ISSUE THREAD

**Issue by pkail** [kristijanhusak/vim-js-file-import#40]
After a delay of about 30 seconds, I get a message saying 'no tag found for word .... '.  I have tried this with various packages.  When I follow the prompts it inserts the import statement properly.

I installed Universal ctags using both the instructions which were given and using Snap.  The only difference is that with Snap, I also get an error saying that gutentags failed.

**Comment by pkail** [comment]
This issue still hasn't been resolved, unfortunately.

**Comment by kristijanhusak** [comment]
Did you try any of the [Performance tips](https://github.com/kristijanhusak/vim-js-file-import#performance-issues)? I'm assuming it takes so long for you because your node_modules are indexed.
On the other side, if there is a match, even after 30 seconds you should get something. Can you open up your `ctags` file and verify that the thing you are trying to import exists?

**Comment by pkail** [comment]
>>Did you try any of the [Performance tips](https://github.com/kristijanhusak/vim-js-file-import#performance-issues)?
Thanks for your help.  I did do this.  However, I still can't get it to work, unfortunately.

The installation instructions suggest that you just need to install ctags and gutentags.  I found that I needed to manually generate a ctags file because gutentags failed to do so.   Ctags generated an endless stream of disk activity and error messages.  However, I still couldn't get the import to work.

I used the ctags-universal snap as a short-cut.  Perhaps it works if you compile the code from source, as suggested.  However, at this stage, ctags seems to be more trouble than it's worth.

**Comment by kristijanhusak** [comment]
Did you try installing https://snapcraft.io/universal-ctags ?

**Comment by pkail** [comment]
I did.  I actually tried a couple of different installations of ctags.

**Comment by kristijanhusak** [comment]
I'm not sure what's the problem, but it seems it's related only to ctags. Once you manage to run `ctags -R .` in your project and get a `tags` file that looks correct and not too big, you should be good to go.

**Comment by pkail** [comment]
Thanks. I've done that, but my experience has been either that the ctags file is gigantic and imports don't work or that it's been a reasonable size, but imports still don't work.  I'll have another go: it would be great to get this working!
